# Generated by Django 5.2.9 on 2025-12-03 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
